# Generated by Django 3.2.25 on 2024-05-23 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_persona'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
