# Generated by Django 5.0.4 on 2024-04-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_created_at_task_engine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.AddField(
            model_name='task',
            name='created_user',
            field=models.CharField(default='DEFAULT_USER'),
        ),
        migrations.AlterField(
            model_name='task',
            name='engine',
            field=models.CharField(default='AWANLLM', max_length=50),
        ),
    ]
