# Generated by Django 5.0.4 on 2024-04-24 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_task_description_task_created_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_user',
            new_name='created_by_user',
        ),
    ]
