# Generated by Django 5.0.4 on 2024-04-24 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_rename_created_user_task_created_by_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='input_value',
        ),
    ]
