# Generated by Django 5.0.4 on 2024-05-02 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_answer_created_by_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='created_by_user',
        ),
    ]
