# Generated by Django 3.2.25 on 2024-05-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('casada', models.CharField(max_length=255)),
                ('extension', models.CharField(max_length=255)),
                ('fechanac', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=255)),
                ('materno', models.CharField(max_length=255)),
                ('nomcompleto', models.CharField(max_length=255)),
                ('nombres', models.CharField(max_length=255)),
                ('nrodocumento', models.CharField(max_length=255)),
                ('nrodocumentochars', models.CharField(max_length=255)),
                ('nrodocumentoint', models.CharField(max_length=255)),
                ('paterno', models.CharField(max_length=255)),
                ('tipodocumento', models.CharField(max_length=255)),
            ],
        ),
    ]
